skills:
  - name: "SQL"
    required: true

  - "Docker"
  - "JavaScript"
  - "React"
  - "Node.js"
  - "Git"
  - "Linux"

salary:
  usd: 3000
  brl: 6000

sites:
  - name: LinkedIn
    url: "https://www.linkedin.com/jobs/search/?keywords=desenvolvedor&location=Brasil&f_WT=2"
    job_selector: ".job-search-card"
    max_jobs: 5
    max_scrolls: 10
    fields:
      title: ".base-search-card__title"
      company: ".base-search-card__subtitle"
      link: ".base-card__full-link"
    detail_fields:
      description: ".description__text"
      salary: ".salary"
      seniority: ".description__job-criteria-text"
    pagination:
      type: "infinite_scroll"
