skills:
  - name: "JavaScript"
    required: true
  - name: "TypeScript"
    required: true
  - "SQL"
  - "ReactJS"
  - "TailwindCSS"
  - "Styled Components"
  - "React Hook Form"
  - "Zod"
  - "Node.js"
  - "REST APIs"
  - "OAuth2"
  - "Docker"
  - "Git"
  - "AWS"
  - "EC2"
  - "S3"
  - "Lambda"
  - "Cognito"
  - "Amplify"
  - "Linux"
  - "React Native"
  - "Java"
  - "Android Studio"
  - "SQLite"
  - "AngularJS"
  - "Scrum"
  - "Payment gateways"
  - "ERP integration"

salary:
  usd: 3000
  brl: 6000

sites:
  - name: LinkedIn Brasil
    url: "https://www.linkedin.com/jobs/search?keywords=Desenvolvedor&location=Brasil&geoId=106057199&f_TPR=&f_WT=2&position=1&pageNum=0"
    job_selector: ".job-search-card"
    max_jobs: 150
    max_scrolls: 50
    fields:
      title: ".base-search-card__title"
      company: ".base-search-card__subtitle"
      link: ".base-card__full-link"
    detail_fields:
      description: ".description__text"
      salary: ".salary"
      seniority: ".description__job-criteria-text"
    pagination:
      type: "infinite_scroll"

  - name: "LinkedIn EUA"
    url: "https://www.linkedin.com/jobs/search?keywords=Developer&location=Estados%20Unidos&geoId=103644278&f_TPR=&f_WT=2&position=1&pageNum=0"
    job_selector: ".job-search-card"
    max_jobs: 150
    max_scrolls: 50
    fields:
      title: ".base-search-card__title"
      company: ".base-search-card__subtitle"
      link: ".base-card__full-link"
    detail_fields:
      description: ".description__text"
      salary: ".salary"
      seniority: ".description__job-criteria-text"
    pagination:
      type: "infinite_scroll"

